//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLExecution.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=%ServerAddress%;Database=%DataBase%;Trusted_Connection=True;")]
        public string DefaultConnectionStringSSPI {
            get {
                return ((string)(this["DefaultConnectionStringSSPI"]));
            }
            set {
                this["DefaultConnectionStringSSPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nServer=%ServerAddress%;Database=%DataBase%;User Id=%UserId%;Password=%Password%" +
            ";")]
        public string DefaultConnectionStringNonSSPI {
            get {
                return ((string)(this["DefaultConnectionStringNonSSPI"]));
            }
            set {
                this["DefaultConnectionStringNonSSPI"] = value;
            }
        }
    }
}
